Move expected tracer.events from test code to golden files
laike9m/Cyberbrain pull request #133
Opened 2021-08-26 02:38 UTC by victorjzsun

Addresses #125. Replaces certain assertions to instead be checked using golden files.

2021-08-28 19:15 UTC, laike9m commented
Generating trace.events JSON from the existing json data files is fine, but eventually we need to be able to dump these JSON from the trace.events in memory. Imagine we add a field to the events, and we definitely don't want to manually update the golden files. We already [support](https://github.com/laike9m/Cyberbrain/blob/master/test/conftest.py#L57-L66) the golden file override feature for mock response, and it would be the same for trace.events.

2021-10-04 05:44 UTC, laike9m commented
I'm working on #126 to support Python 3.10. 3.10 changes bytecode quite a bit, and hard-code `trace.events` in test doesn't really work. I'm looking forward to this feature😀

Btw, do you think `get_value` in `test/utils.py` can be removed once this is in?

2021-10-04 22:53 UTC, victorjzsun commented
> I'm working on #126 to support Python 3.10. 3.10 changes bytecode quite a bit, so hard-code `trace.events` in test doesn't work anymore. I'm looking forward to this feature😀
> 
> Btw, do you think `get_value` in `test/utils.py` can be removed once this is in?

`get_value` is also used in `tracer.loops` assertions so not yet. I was planning on just focusing on `tracer.events` for this PR and deal with `tracer.loops` assertions in the next PR.

2021-10-05 06:56 UTC, laike9m commented on cyberbrain/basis.py
> +        if field is None:
why do we need this?

2021-10-05 07:09 UTC, laike9m commented on test/conftest.py
> +        if golden_frame_data.get("response", None) is None:
> If default is not given, it defaults to None
so `None` is not needed here

2021-10-05 07:24 UTC, laike9m commented on test/conftest.py
> +def check_response(request):
I feel like this function is doing multiple things and we should break into smaller ones, something like

```python
golden_response = get_golden_response()
if golden_response:
  assert ...
else:
  update_golden_response()
```

This makese the intent more clear. A good side effect: skip assertion if golden_response does not exist (now assertion still happens if the file exists).

2021-10-05 07:30 UTC, laike9m commented on test/conftest.py
> +        }
you can do

```python
# If snap shot is None, keep it.
snapshot = snapshot and {
    "location": symbol.snapshot.location,
    "events_pointer": symbol.snapshot.events_pointer,
}
```

2021-10-05 07:31 UTC, laike9m commented on test/conftest.py
> +    tracer_events = []
this can be extracted to a separate function.

2021-10-05 07:32 UTC, laike9m commented on test/conftest.py
> +def check_response(request):
Same with `check_tracer_events`

2021-10-05 07:32 UTC, laike9m requested changes
left some comments

2021-10-07 14:18 UTC, victorjzsun commented
> Nvm, I just find that I can squash myself

Only collaborators have merge access so I can't even merge it regardless.

2021-10-08 03:35 UTC, merged